name: torchdata
channels:
  - pytorch-nightly
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - python=3.8.0
  - ipython=8.4.0
  - pytorch=2.0.*
  - torchvision=0.15.*
  - pytorch-cuda=11.6
  - torchdata=0.6.*
  - torchtext=0.15.*
  - libjpeg-turbo=2.1.*
  - ipykernel=6.19.*
  - kaggle=1.5.*
  - svn=1.10.*
  - nb_conda_kernels=2.3.*
  - pip
  - pip:
    - https://download.pytorch.org/whl/nightly/torcharrow-0.2.0a0.dev20230201-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
    - tqdm==4.64.1
    - webdataset==0.2.31
    - dill==0.3.6
    - pandas==1.3.5
    - graphviz==0.20.1
    - kornia==0.6.9
    - ipywidgets==7.7.2
    - aistore==1.0.7
    - sagemaker==2.129.0
    - datasets==2.9.0
    - pycocotools==2.0.6
    - pyarrow==11.0.0
    - pillow-simd==9.0.0.post1